## For debian distros. For RHEL change apt-get to yum

FROM python:3.8-slim
#FROM registry.access.redhat.com/ubi8/python-38

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    libpq-dev

# Set the working directory
WORKDIR /app

# Copy the requirements.txt file
COPY requirements.txt .

# Install the requirements
RUN pip install -r requirements.txt

# Copy the rest of the files
COPY . .

# Run a script 
RUN python3 replace.py

# Expose the port
EXPOSE 5000

# Run the app
CMD ["python3", "app.py"]

